spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:tcp://localhost/~/freetest
    url: jdbc:h2:~/freetest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  cache:    type: redis
  redis:    host: localhost
    port: 6379
logging.level:
  org.hibernate.SQL: debug
#server:
#  port: 8080
#logging.level:
#  org.hibernate.SQL: debug
#spring:
#  messages:
#    basename: i18n/messages
#    encoding: UTF-8
#    cache-duration: PT1H
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/freepjt?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: ssafy
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        default_batch_fetch_size: 1000
#        format_sql: true
#    open-in-view: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
cloud:
  aws:
    credentials:
      accessKey: AKIAVISGU4KSDZTO6LHK
      secretKey: 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
    s3:
      bucket: freepjt
    region:
      static: ap-northeast-2
    stack:
      auto: false
  
jwt:
  header: Authorization
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 1800
  refresh_expiration: 86400
  
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
