spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:tcp://localhost/~/freetest
    url: jdbc:h2:~/freetest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      accessKey: AKIAVISGU4KSDZTO6LHK
      secretKey: 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
    s3:
      bucket: freepjt
    region:
      static: ap-northeast-2
    stack:
      auto: false
  
jwt:
  header: Authorization
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 86400
